
"use client"
import OrganizationTable from '@/app/components/organization/OrganizationTable'
import reportsData from '@/app/data/reports'
import React from 'react'

export default function page() {

  let Recruitment = reportsData.filter(
    (item) => item.module === "recruitment-reports")

  let columns = [
    {
      key: "reportName",
      label: "report Name"
    },
    {
      key: "reportType",
      label: "report Type"
    },
    {
      key: "generatedBy",
      label: "generated By"
    },
    {
      key: "generatedDate",
      label: "generated Date"
    },
    {
      key: "status",
      label: "status"
    },
  ]

  const view = (row) => {
    console.log(row)
  }

  const Edit = (row) => {
    console.log(row)
  }

  const Delete = (row) => {
    console.log(row)
  }

  return (
    <div>
      <OrganizationTable data={Recruitment}
        columns={columns}
        View={view}
        Edit={Edit}
        Delete={Delete}
        basePath="/admin/reports/recruitment-reports"
      />
    </div>
  )
}
